### PR TITLE
[#86832570] allow access token to be passed in

### PR DESCRIPTION
**Pull request by kaitlinr**
Update our local copy (this commit fixes an issue with refreshing our token:  https://github.com/ExactTarget/FuelSDK-Ruby/commit/c7b49f645e9949b56847ecbdd433e1b2a7da83c1).

Also, add the ability to pass in access tokens - this should save some token refresh calls.

### CODE REVIEW

**Comment by schonstal** [comment]
:+1:

**Comment by stopdropandrew** [comment]
I don't think we should merge this

**Comment by yukster** [comment]
Whoops, you were a little late @stopdropandrew.

**Comment by kaitlinr** [comment]
Reverted the commit with new code I added.  Left the commits I merged in from the upstream master.  Though I think we can just pull directly from ET's github, so working on that change.

**Pull request merged**
